const SEED_DATA = {
  hospitals: [
    {
      id: "hosp-1",
      _id: "hosp-1",
      name: "All India Institute of Medical Sciences (AIIMS)",
      city: "New Delhi",
      address: "Sri Aurobindo Marg, Ansari Nagar, New Delhi - 110029",
      phone: "+91 11 2658 8500",
      lat: 28.5672,
      lng: 77.2100,
      specialties: ["Cardiology", "Neurology", "Oncology", "Orthopedics", "Pediatrics", "General Medicine"],
      rating: 4.9,
      cost_tier: "low",
      emergency_24x7: true,
      has_icu: true,
      has_mri: true,
      has_ambulance: true,
      is_government: true,
      ayushman: true,
      image_url: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=800&auto=format&fit=crop&q=60",
      beds: {
        icu_available: 18,
        icu_total: 60,
        oxygen_available: 45,
        oxygen_total: 120,
        emergency_available: 12,
        emergency_total: 30,
        general_available: 110,
        general_total: 400,
      },
    },
    {
      id: "hosp-2",
      _id: "hosp-2",
      name: "Apollo Hospitals, Bannerghatta",
      city: "Bengaluru",
      address: "154/11, Opp. IIM-B, Bannerghatta Road, Bengaluru - 560076",
      phone: "+91 80 2630 4050",
      lat: 12.8958,
      lng: 77.5989,
      specialties: ["Cardiology", "Neurology", "Orthopedics", "Gynaecology", "Oncology"],
      rating: 4.7,
      cost_tier: "high",
      emergency_24x7: true,
      has_icu: true,
      has_mri: true,
      has_ambulance: true,
      is_government: false,
      ayushman: true,
      image_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=60",
      beds: {
        icu_available: 8,
        icu_total: 40,
        oxygen_available: 24,
        oxygen_total: 80,
        emergency_available: 6,
        emergency_total: 20,
        general_available: 65,
        general_total: 250,
      },
    },
    {
      id: "hosp-3",
      _id: "hosp-3",
      name: "Christian Medical College (CMC)",
      city: "Vellore",
      address: "Ida Scudder Road, Vellore, Tamil Nadu - 632004",
      phone: "+91 416 228 1000",
      lat: 12.9246,
      lng: 79.1348,
      specialties: ["General Medicine", "Cardiology", "Neurology", "Pediatrics", "Dermatology", "ENT"],
      rating: 4.8,
      cost_tier: "medium",
      emergency_24x7: true,
      has_icu: true,
      has_mri: true,
      has_ambulance: true,
      is_government: false,
      ayushman: true,
      image_url: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&auto=format&fit=crop&q=60",
      beds: {
        icu_available: 14,
        icu_total: 50,
        oxygen_available: 38,
        oxygen_total: 100,
        emergency_available: 9,
        emergency_total: 25,
        general_available: 90,
        general_total: 350,
      },
    },
    {
      id: "hosp-4",
      _id: "hosp-4",
      name: "Fortis Hospital, Mulund",
      city: "Mumbai",
      address: "Mulund Goregaon Link Road, Industrial Area, Mulund West, Mumbai - 400078",
      phone: "+91 22 4365 4365",
      lat: 19.1663,
      lng: 72.9362,
      specialties: ["Cardiology", "Orthopedics", "Neurology", "Oncology", "Dental"],
      rating: 4.6,
      cost_tier: "high",
      emergency_24x7: true,
      has_icu: true,
      has_mri: true,
      has_ambulance: true,
      is_government: false,
      ayushman: false,
      image_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=60",
      beds: {
        icu_available: 5,
        icu_total: 35,
        oxygen_available: 18,
        oxygen_total: 60,
        emergency_available: 4,
        emergency_total: 15,
        general_available: 42,
        general_total: 180,
      },
    },
    {
      id: "hosp-5",
      _id: "hosp-5",
      name: "Manipal Hospital",
      city: "Bengaluru",
      address: "98, HAL Old Airport Rd, Kodihalli, Bengaluru - 560017",
      phone: "+91 80 2502 4444",
      lat: 12.9592,
      lng: 77.6496,
      specialties: ["Cardiology", "Pediatrics", "Oncology", "Orthopedics", "Gynaecology"],
      rating: 4.5,
      cost_tier: "medium",
      emergency_24x7: true,
      has_icu: true,
      has_mri: true,
      has_ambulance: true,
      is_government: false,
      ayushman: true,
      image_url: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&auto=format&fit=crop&q=60",
      beds: {
        icu_available: 11,
        icu_total: 45,
        oxygen_available: 30,
        oxygen_total: 90,
        emergency_available: 8,
        emergency_total: 20,
        general_available: 78,
        general_total: 280,
      },
    },
    {
      id: "hosp-6",
      _id: "hosp-6",
      name: "Kokilaben Dhirubhai Ambani Hospital",
      city: "Mumbai",
      address: "Rao Saheb, Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai - 400053",
      phone: "+91 22 4269 6969",
      lat: 19.1312,
      lng: 72.8258,
      specialties: ["Neurology", "Cardiology", "Oncology", "Orthopedics", "Pediatrics", "Dermatology"],
      rating: 4.8,
      cost_tier: "high",
      emergency_24x7: true,
      has_icu: true,
      has_mri: true,
      has_ambulance: true,
      is_government: false,
      ayushman: false,
      image_url: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=60",
      beds: {
        icu_available: 7,
        icu_total: 50,
        oxygen_available: 22,
        oxygen_total: 75,
        emergency_available: 5,
        emergency_total: 20,
        general_available: 55,
        general_total: 220,
      },
    },
  ],
  doctors: [
    {
      id: "doc-1",
      _id: "doc-1",
      name: "Ramesh Sharma",
      specialization: "Cardiology",
      hospital_id: "hosp-1",
      experience_years: 18,
      consultation_fee: 100,
      rating: 4.9,
      timing: "9:00 AM - 1:00 PM",
      available_days: ["Mon", "Wed", "Fri"],
      avatar_url: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=60",
      hospitals: { name: "All India Institute of Medical Sciences (AIIMS)", city: "New Delhi" },
      hospital: { name: "All India Institute of Medical Sciences (AIIMS)", city: "New Delhi" },
    },
    {
      id: "doc-2",
      _id: "doc-2",
      name: "Priya Venkatesh",
      specialization: "Neurology",
      hospital_id: "hosp-1",
      experience_years: 14,
      consultation_fee: 100,
      rating: 4.8,
      timing: "10:00 AM - 2:00 PM",
      available_days: ["Tue", "Thu", "Sat"],
      avatar_url: "https://images.unsplash.com/photo-1594824813501-48c9735d4695?w=300&auto=format&fit=crop&q=60",
      hospitals: { name: "All India Institute of Medical Sciences (AIIMS)", city: "New Delhi" },
      hospital: { name: "All India Institute of Medical Sciences (AIIMS)", city: "New Delhi" },
    },
    {
      id: "doc-3",
      _id: "doc-3",
      name: "Anil Kumar",
      specialization: "Orthopedics",
      hospital_id: "hosp-2",
      experience_years: 12,
      consultation_fee: 800,
      rating: 4.7,
      timing: "11:00 AM - 4:00 PM",
      available_days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      avatar_url: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=60",
      hospitals: { name: "Apollo Hospitals, Bannerghatta", city: "Bengaluru" },
      hospital: { name: "Apollo Hospitals, Bannerghatta", city: "Bengaluru" },
    },
    {
      id: "doc-4",
      _id: "doc-4",
      name: "Sunita Menon",
      specialization: "Pediatrics",
      hospital_id: "hosp-3",
      experience_years: 16,
      consultation_fee: 400,
      rating: 4.9,
      timing: "9:00 AM - 3:00 PM",
      available_days: ["Mon", "Wed", "Fri", "Sat"],
      avatar_url: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=60",
      hospitals: { name: "Christian Medical College (CMC)", city: "Vellore" },
      hospital: { name: "Christian Medical College (CMC)", city: "Vellore" },
    },
    {
      id: "doc-5",
      _id: "doc-5",
      name: "Vikram Mehta",
      specialization: "Cardiology",
      hospital_id: "hosp-4",
      experience_years: 20,
      consultation_fee: 1200,
      rating: 4.8,
      timing: "2:00 PM - 7:00 PM",
      available_days: ["Tue", "Thu", "Sat"],
      avatar_url: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=60",
      hospitals: { name: "Fortis Hospital, Mulund", city: "Mumbai" },
      hospital: { name: "Fortis Hospital, Mulund", city: "Mumbai" },
    },
  ],
  blood_banks: [
    {
      id: "bb-1",
      _id: "bb-1",
      name: "Indian Red Cross Society Blood Bank",
      city: "New Delhi",
      address: "1, Red Cross Road, Near Parliament Street, New Delhi - 110001",
      phone: "+91 11 2371 1551",
      available_groups: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"],
    },
    {
      id: "bb-2",
      _id: "bb-2",
      name: "Lions Club Blood Bank",
      city: "Mumbai",
      address: "Plot 37, Sector 15, Vashi, Navi Mumbai - 400703",
      phone: "+91 22 2789 2200",
      available_groups: ["A+", "B+", "O+", "AB+"],
    },
    {
      id: "bb-3",
      _id: "bb-3",
      name: "Rotary TTK Blood Bank",
      city: "Bengaluru",
      address: "New Thippasandra Main Road, HAL 3rd Stage, Bengaluru - 560075",
      phone: "+91 80 2528 7903",
      available_groups: ["A+", "A-", "B+", "O+", "O-"],
    },
  ],
  pharmacies: [
    {
      id: "ph-1",
      _id: "ph-1",
      name: "Apollo Pharmacy - 24/7 Central",
      city: "New Delhi",
      address: "Shop 12, AIIMS Metro Station Complex, New Delhi",
      phone: "+91 11 2658 9911",
      open_24x7: true,
      home_delivery: true,
      medicines: ["Paracetamol", "Azithromycin", "Insulin", "Amoxicillin", "Metformin", "Amlodipine", "Pantoprazole"],
    },
    {
      id: "ph-2",
      _id: "ph-2",
      name: "MedPlus 24 Hours",
      city: "Bengaluru",
      address: "45/2, 80 Feet Road, 4th Block, Koramangala, Bengaluru",
      phone: "+91 80 2553 4411",
      open_24x7: true,
      home_delivery: true,
      medicines: ["Paracetamol", "Cetirizine", "Ibuprofen", "Atorvastatin", "Losartan", "Omeprazole"],
    },
    {
      id: "ph-3",
      _id: "ph-3",
      name: "Wellness Forever 24x7",
      city: "Mumbai",
      address: "Ground Floor, Hill Road, Bandra West, Mumbai",
      phone: "+91 22 2640 5500",
      open_24x7: true,
      home_delivery: true,
      medicines: ["Paracetamol", "Dolo 650", "Augmentin", "Telmisartan", "Glycomet", "Pan-D"],
    },
  ],
  schemes: [
    {
      id: "sch-1",
      _id: "sch-1",
      name: "Ayushman Bharat - PM-JAY",
      description: "World's largest health assurance scheme providing ₹5 lakh per family per year for secondary and tertiary care hospitalization.",
      eligibility: "Deprived rural families and identified occupational categories of urban workers based on SECC 2011.",
      benefits: "Cashless coverage of up to ₹5,00,000 per family per year across empaneled public and private hospitals.",
      link: "https://pmjay.gov.in",
    },
    {
      id: "sch-2",
      _id: "sch-2",
      name: "Central Government Health Scheme (CGHS)",
      description: "Comprehensive medical care facilities for Central Government employees, pensioners, and their dependents.",
      eligibility: "Serving and retired Central Govt employees and accredited journalists.",
      benefits: "OPD and IPD facilities, specialist consultations, and reimbursement of emergency treatments.",
      link: "https://cghs.nic.in",
    },
    {
      id: "sch-3",
      _id: "sch-3",
      name: "Pradhan Mantri Swasthya Suraksha Yojana (PMSSY)",
      description: "Aimed at correcting regional imbalances in the availability of affordable and reliable tertiary healthcare services.",
      eligibility: "Open to all Indian citizens at established AIIMS-like apex medical institutes.",
      benefits: "Super-specialty healthcare and medical education access at government rates.",
      link: "https://pmssy.mohfw.gov.in",
    },
  ],
  emergency_contacts: [
    { id: "ec-1", _id: "ec-1", label: "National Emergency Number", number: "112", category: "all-in-one" },
    { id: "ec-2", _id: "ec-2", label: "Ambulance Helpline", number: "102", category: "medical" },
    { id: "ec-3", _id: "ec-3", label: "Emergency Disaster Management", number: "108", category: "medical" },
    { id: "ec-4", _id: "ec-4", label: "Police Control Room", number: "100", category: "police" },
    { id: "ec-5", _id: "ec-5", label: "Fire & Rescue", number: "101", category: "fire" },
    { id: "ec-6", _id: "ec-6", label: "Women in Distress Helpline", number: "1091", category: "women" },
    { id: "ec-7", _id: "ec-7", label: "Child Helpline", number: "1098", category: "child" },
  ],
};

module.exports = SEED_DATA;
