export const adminAnalytics = async () => ({ counts: {}, topCities: [] });
export const adminCheckSelf = async () => ({ isAdmin: true });
export const adminListPending = async () => [];
export const adminApproveHospital = async () => {};
export const adminRejectHospital = async () => {};
export const adminListMessages = async () => [];
export const adminResolveMessage = async () => {};
export const adminListDoctors = async () => [];
export const adminCreateDoctor = async () => {};
export const adminUpdateDoctor = async () => {};
export const adminDeleteDoctor = async () => {};
export const adminCreateHospital = async () => {};
export const adminUpdateHospital = async () => {};
export const adminDeleteHospital = async () => {};
export const adminListDepartments = async () => [];
export const adminCreateDepartment = async () => {};
export const adminDeleteDepartment = async () => {};
export const adminListFacilities = async () => [];
export const adminCreateFacility = async () => {};
export const adminDeleteFacility = async () => {};
